# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: |
          curl https://sh.rustup.rs -sSf -o install_rust.sh
          chmod +x install_rust.sh
          ./install_rust.sh -q -y
          rm install_rust.sh
          export PATH="${HOME}/.cargo/bin:${PATH}"
          rustc -V      
      - run: mix deps.get
      - run: make init-contracts
      - run: |
          export PATH="${HOME}/.cargo/bin:${PATH}"
          mix test